[colors]
[colors.primary]
background = "#121212"
foreground = "#ffffff"

[colors.normal]
black   = "#121212"
red     = "#d58572"
green   = "#80b780"
yellow  = "#bdbd89"
blue    = "#e4a067"
magenta = "#ce7e8a"
cyan    = "#927ece"
white   = "#faf9f9"

[colors.bright]
black   = "#5e5e5e"
red     = "#de9d8e"
green   = "#b9dab9"
yellow  = "#dfdfc3"
blue    = "#e4a067"
magenta = "#ce7e8a"
cyan    = "#927ece"
white   = "#ffffff"

[colors.cursor]
text   = "#121212"
cursor = "#ffffff"
